CREATE TABLE IF NOT EXISTS sales (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by int4 NOT NULL,
	status varchar(255) NOT NULL,
	updated_at timestamp(6) NULL,
	updated_by int4 NULL,
	"comment" varchar(255) NULL,
	sale_date timestamp(6) NOT NULL,
	total numeric(38, 4) NOT NULL,
	user_id int4 NOT NULL,
	CONSTRAINT sales_pkey PRIMARY KEY (id),
	CONSTRAINT sales_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);

ALTER TABLE sales ADD CONSTRAINT fk5bgaw8g0rrbqdvafq36g58smk FOREIGN KEY (user_id) REFERENCES users(id);


CREATE TABLE IF NOT EXISTS sales_details (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by int4 NOT NULL,
	status varchar(255) NOT NULL,
	updated_at timestamp(6) NULL,
	updated_by int4 NULL,
	amount int4 NOT NULL,
	subtotal numeric(38, 4) NOT NULL,
	unit_sales_price numeric(38, 4) NOT NULL,
	batch_id int4 NOT NULL,
	product_id int4 NOT NULL,
	sale_id int4 NOT NULL,
	CONSTRAINT sales_details_pkey PRIMARY KEY (id),
	CONSTRAINT sales_details_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);

ALTER TABLE sales_details ADD CONSTRAINT fk3g4pbmghp5kni384fahr2us74 FOREIGN KEY (sale_id) REFERENCES sales(id);
ALTER TABLE sales_details ADD CONSTRAINT fkodu037j7ltj1meocsdn00ruby FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE sales_details ADD CONSTRAINT fkqyjshwalf9d98406aw9f8q6p FOREIGN KEY (batch_id) REFERENCES batch_stock(id);
