CREATE TABLE IF NOT EXISTS products (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by int4 NOT NULL,
	status varchar(255) NOT NULL,
	updated_at timestamp(6) NULL,
	updated_by int4 NULL,
	code varchar(100) NOT NULL,
	"name" varchar(100) NOT NULL,
	sale_price numeric(38, 4) NOT NULL,
	umbral_stock int4 NOT NULL,
	CONSTRAINT products_pkey PRIMARY KEY (id),
	CONSTRAINT products_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


CREATE TABLE IF NOT EXISTS providers (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by int4 NOT NULL,
	status varchar(255) NOT NULL,
	updated_at timestamp(6) NULL,
	updated_by int4 NULL,
	direction varchar(100) NOT NULL,
	email varchar(100) NOT NULL,
	"name" varchar(100) NOT NULL,
	phone varchar(20) NOT NULL,
	CONSTRAINT providers_pkey PRIMARY KEY (id),
	CONSTRAINT providers_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[]))),
	CONSTRAINT uk7ant8u8y5lel5bd0d6hdexmde UNIQUE (email),
	CONSTRAINT ukpkm9de2qdqtjo8dbad3fwf4ft UNIQUE (phone)
);


CREATE TABLE IF NOT EXISTS batch_stock (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by int4 NOT NULL,
	status varchar(255) NOT NULL,
	updated_at timestamp(6) NULL,
	updated_by int4 NULL,
	acquisition_date date NOT NULL,
	expiration_date date NOT NULL,
	initial_amount int4 NOT NULL,
	purchase_price numeric(38, 4) NOT NULL,
	product_id int4 NOT NULL,
	provider_id int4 NOT NULL,
	CONSTRAINT batch_stock_pkey PRIMARY KEY (id),
	CONSTRAINT batch_stock_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


ALTER TABLE batch_stock ADD CONSTRAINT fk962gp2ip54di8bpx0plv8p4n FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE batch_stock ADD CONSTRAINT fk96pwgii3xeumyjxs5iswq0k27 FOREIGN KEY (provider_id) REFERENCES providers(id);
