CREATE TABLE IF NOT EXISTS users (
	created_by int4 NOT NULL,
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	updated_by int4 NULL,
	created_at timestamp(6) NOT NULL,
	updated_at timestamp(6) NULL,
	first_name varchar(50) NOT NULL,
	email varchar(100) NOT NULL,
	last_name varchar(100) NULL,
	"password" varchar(100) NOT NULL,
	username varchar(100) NOT NULL,
	status varchar(255) NOT NULL,
	CONSTRAINT users_email_key UNIQUE (email),
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[]))),
	CONSTRAINT users_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS roles (
	created_by int4 NOT NULL,
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	updated_by int4 NULL,
	created_at timestamp(6) NOT NULL,
	updated_at timestamp(6) NULL,
	description varchar(255) NULL,
	"role" varchar(255) NULL,
	status varchar(255) NOT NULL,
	CONSTRAINT roles_pkey PRIMARY KEY (id),
	CONSTRAINT roles_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying])::text[]))),
	CONSTRAINT roles_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS user_role (
	created_by int4 NOT NULL,
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	role_id int4 NOT NULL,
	updated_by int4 NULL,
	user_id int4 NOT NULL,
	created_at timestamp(6) NOT NULL,
	updated_at timestamp(6) NULL,
	status varchar(255) NOT NULL,
	CONSTRAINT user_role_pkey PRIMARY KEY (id),
	CONSTRAINT user_role_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);

ALTER TABLE public.user_role ADD CONSTRAINT fkj345gk1bovqvfame88rcx7yyx FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE public.user_role ADD CONSTRAINT fkt7e7djp752sqn6w22i6ocqy6q FOREIGN KEY (role_id) REFERENCES public.roles(id);
