CREATE TABLE kardex (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by int4 NOT NULL,
	status varchar(255) NOT NULL,
	updated_at timestamp(6) NULL,
	updated_by int4 NULL,
	amount int4 NOT NULL,
	balance_amount numeric(38, 2) NULL,
	movement_type varchar(255) NOT NULL,
	reference varchar(255) NULL,
	total_price numeric(38, 2) NULL,
	unit_price numeric(38, 2) NOT NULL,
	batch_id int4 NOT NULL,
	product_id int4 NOT NULL,
  reference_id int4 NOT NULL,
	CONSTRAINT kardex_pkey PRIMARY KEY (id),
	CONSTRAINT kardex_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


-- public.kardex foreign keys

ALTER TABLE kardex ADD CONSTRAINT fka2sqr7uuc2l8f0543llm8uv2u FOREIGN KEY (batch_id) REFERENCES batch_stock(id);
ALTER TABLE kardex ADD CONSTRAINT fkoy4sn315wjdgxdkobgemm4fty FOREIGN KEY (product_id) REFERENCES products(id);
